apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: accounts
build:
  artifacts:
  - image: didoux/accounts
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/5_accounts.yml
