apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: gatewayserver
build:
  artifacts:
  - image: didoux/gatewayserver
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/8_gateway.yml
