apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: configservice
build:
  artifacts:
    - image: didoux/configserver
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/3_configserver.yml
